name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: FoodMVCWebApp    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: 'FoodMVCWebApp'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.x'                 # set this to the .NET Core version to use
  
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Build app
        run: dotnet build -c Release ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --no-restore

      - name: Test app
        run: dotnet test FoodMVCWebApp --no-restore --verbosity normal

      - name: dotnet publish
        run: dotnet publish -c Release ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} -o ${{env.DOTNET_ROOT}}/package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: net-app
          path: ${{env.DOTNET_ROOT}}/package
          if-no-files-found: error

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: net-app
          path: net-app       

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: net-app
